name: "Publish image"

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Prepare Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch,enable=${{ github.ref == 'refs/heads/master' }}
            type=sha,format=long,enable=${{ github.ref == 'refs/heads/master' }}
            type=semver,pattern={{version}},enable=${{ contains(github.ref, 'refs/tags/v') }}
          flavor: latest=${{ github.ref == 'refs/heads/master' }}
      - name: Build and push accelerated-bridge-cni
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: ./Dockerfile
